"""initial schema

Revision ID: 6045c769f24b
Revises:
Create Date: 2025-06-14 15:44:28.843821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6045c769f24b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("ext_meta_logging",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
