"""initial schema

Revision ID: 6c731c4a695d
Revises:
Create Date: 2025-06-14 15:44:26.153336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c731c4a695d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("ext_database",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
