"""Initial migration

Revision ID: ee80e1858d77
Revises:
Create Date: 2025-06-12 00:59:03.052953

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee80e1858d77"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ("ext_payment",)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "external_payment_id",
            sa.String(),
            nullable=True,
            comment="External subscription ID from payment provider",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "external_payment_id")
    # ### end Alembic commands ###
